### ISSUE TITLE
SCP: sim_printf does not properly handle sim_printf("\n");

### ISSUE THREAD

**Issue by deltecent** [open-simh/simh#124]
```sim_printf("\n")``` sends only a "\n" rather than a "\r\n".

```
char *c, *remnant = buf;

    while ((c = strchr (remnant, '\n'))) {
        if ((c != buf) && (*(c - 1) != '\r'))
            fprintf (stdout, "%.*s\r\n", (int)(c-remnant), remnant);
        else
            fprintf (stdout, "%.*s\n", (int)(c-remnant), remnant);
        remnant = c + 1;
        }
    fprintf (stdout, "%s", remnant);
```

When printing only "\n", c == buf so a "\r" is not sent along with the "\n".  ```sim_printf("_\n")``` sends "_\r\n".

```
sim> show version
Altair 8800 (Z80) simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC Apple LLVM 12.0.0 (clang-1200.0.32.2)
        Simulator Compiled as C arch: x64 (Release Build) on Nov 20 2022 at 19:59:26
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.43 2019-02-23) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Darwin Patricks-iMac.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jun 21 21:18:39 PDT 2022; root:xnu-6153.141.66~1/RELEASE_X86_64 x86_64
        Processor Name: Intel(R) Core(TM) i5-4570R CPU @ 2.70GHz
        tar tool: bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
        curl tool: curl 7.78.0 (x86_64-apple-darwin13.4.0) libcurl/7.78.0 OpenSSL/1.1.1l zlib/1.2.11 libssh2/1.9.0 nghttp2/1.41.0
        git commit id: ffd93046+uncommitted-changes
        git commit time: 2022-11-20T12:43:37-0800
```

Actual output:

```
sim> s

Step expired
            C0Z0M0E0I0 A=00 B=0000 D=0000 H=0000 S=0000 P=0002 NOP
                                                                  sim> s

Step expired
            C0Z0M0E0I0 A=00 B=0000 D=0000 H=0000 S=0000 P=0003 NOP
                                                                  sim>
```

Expected output:

```
sim> s

Step expired
C0Z0M0E0I0 A=00 B=0000 D=0000 H=0000 S=0000 P=0001 NOP 
sim> s

Step expired
C0Z0M0E0I0 A=00 B=0000 D=0000 H=0000 S=0000 P=0002 NOP 
sim>
```

**Comment by markpizz** [comment]
This is when you're handling your own message output before returning form sim_instr().

The issues that while sim_instr() is running, the console port is in binary mode (which means that "\n" is not translated to "\r\n").  If you want "\r\n", you've got to be specific.

After sleeping on things, emitting your own messages before sim_instr() returns isn't the right approach.

Consider this approach which doesn't require any sim_vm_stopped replacement, and puts precisely what you want on 2 lines:

```
sim> SET ON
sim> ON STEP <your-extra-command-to-display-fantastic-things>
sim> ON STOP <your-extra-command-to-display-fantastic-things>
```

What's happening here is you add a command called whatever (your-extra-command-to-display-fantastic-things) which will get called as the next command before the sim> prompt is issued.  The normal STEP or STOP message will be displayed (indicating the PC and the instruction it points at), and then your extra command will emit whatever you want formatted however you want.  There are other simulators which define sim_vm_cmd to extend or replace the SCP commands.

This gets you there with no cross SCP/simulator behaviors.  

Let me know your thoughts.

**Comment by deltecent** [comment]
I don’t like it as much as, especially since it ends up printing out superfluous information, requires more keystrokes, and I already have it working the other way, but it is certainly worth looking at. Is it possible to get a list of commands that are available?

I tried “ON BREAK”, which is an AltairZ80 extra command, and what I get is: 

sim> on break echo Break!!!
Invalid argument: BREAK
sim>

**Comment by markpizz** [comment]
The values following the word "ON" are specific error codes (SCPE_xxxx) text or numeric values for xxxx.  If your driving script otherwise doesn't deal with error trapping, then the general word ERROR covers everything:
```
sim> # enable error trapping:
sim> SET ON 
sim> # trap all non 0 values
sim> ON ERROR Echo %STATUS%-%TSTATUS%
sim> # specifically for your extended command passing status in case it is interesting...
sim> ON ERROR <your-extended-command> %STATUS%
```
You wouldn't have to type the above except once into an init file: ~/simh.ini

**Comment by deltecent** [comment]
>If your driving script otherwise doesn't deal with error trapping, then the general word ERROR covers everything:

Are you saying that if there are 5 different conditions that can cause a VM to stop, we can only set a single "ON" condition of "ERROR"?

If that is the case, I very much prefer the VM being able to handle VM-specific traps for users of that specific VM, not something that is generic and not as flexible. Considering these are not "errors" per se, it seems STEP, BREAK, and other tools should be handled differently than an actual ERRORs like "File Not Found" or "The VM Just Blew Up".

The AltairZ80 is used by people that do more than boot CP/M to run Zork and Star Trek. Many users also have real hardware and use the VM as part of working with that hardware. That is the reason we've added support for Tarbell, iCOM, Jade DD, modems, etc. We can work with this "hardware" in a VM and then transfer our work to the real hardware. The intention of these PRs is to make that job easier without impacting the other VMs and their unique requirements. These PRs are adding features that should be invisible to people that don't need them. SCP is general purpose. AltairZ80 is specific.

> The issues that while sim_instr() is running, the console port is in binary mode (which means that "\n" is not translated to "\r\n"). If you want "\r\n", you've got to be specific.

I was just pointing out that sim_printf while sim_instr() is running will translate "x\n" to "x\r\n", "x\nx\n" to "x\r\nx\r\n" and "\n" to "\n". I don't know if that was the intent. These produce different outputs when I thought they would be identical:

```
sim_printf("Hello\n");
sim_printf("Hello\n");

Hello
Hello
simh>
```
```
sim_printf("Hello");
sim_print("\n");
sim_printf("Hello");
sim_print("\n");

Hello
     Hello
          sim>
```

**Comment by markpizz** [comment]
ERROR means any value other than 0 (SCPE_OK).
Look at sim_defs.h for the definitions of the various SCPE_xxxx values.

```
ON OPENERR echo an OPENERR was returned
ON UNATT echo something was unattached
ON NXM echo something returned with SCPE_NXM
ON 64 echo something returned with SCPE_NXM
...
ON 26 echo something returned error # 26
```

repeat for every possible value that could be returned from 1 thru SCPE_MAX_ERR.

Meanwhile the issue you notice with sim_printf() when the simulator is running really shouldn't be changed.  This is due to the fact that sim_printf() SHOULD NOT EVER be used in simulation code (i.e. devices runtime logic, vs setup logic, and processor simulation logic).  There are specific API's that write to the console device that correctly interact with how things behave when the simulator is running, and sim_printf() is not intended to go there.

**Comment by deltecent** [comment]
> There are specific API's that write to the console device that correctly interact with how things behave when the simulator is running

Which specific APIs should be used to write to the console when the simulator is running? sim_putchar?

I see the use of sim_printf  in quite a few places that appear to be while the simulator is running. Maybe add an "if sim_is_running" to sim_printf to give a message of the correct API to use as sim_printf seems like the logical function to use to print a formatted string, there is nothing the comments giving a warning about its misuse, and nothing the _Writing a Simulator_ doc.

```
/* Print message to stdout, sim_log (if enabled) and sim_deb (if enabled) */
/* BUT NOT IF THE SIMULATOR IS RUNNING... USE XXXX INSTEAD */
void sim_printf (const char* fmt, ...)
{
```

**Comment by markpizz** [comment]
There is a fundamental distinction between the simulator's console device and the session which initiates the simulator's execution.  sim_printf() and the rest of SCP directly interacts with the session that initiates the simulator's execution and correctly does so during various configuration activities simulators support to configure, and customize the details of the setup and operation of the simulator and it's devices.  These are appropriate in device attach routines, and MTAB action routines.  

The simulator's console device defaults to coincide with the session that initiates the simulator's execution, but is operationally distinct and can readily be attached to a telnet session or serial port which then is completely independent of interactions in the session that initiates (and controls) the simulator's execution.

You ask:
> Which specific APIs should be used to write to the console when the simulator is running? sim_putchar?

I'm not familiar with the specifics of operation of your favorite simulator (AltairZ80), so I can't say whether the distinction I described above between the session that initiates and controls the simulator execution is separate from a console device which the simulated system may (or may not) have.  Most other simulators have such a distinction.  The console device is an I/O device that exists in the simulated system and instructions (via various means) running in the simulator can do I/O to this device.  Given this lack of knowing about the console vs session distinction, I can't reasonably answer your question.  The comment before the sim_printf() API specifically refers to SCP provided features that relate to the session that initiated the simulation and absolutely nothing about the device which implements the console port of a system.  Think about this:  in general, most simulated CPU's don't have an instruction which translates to the equivalent of a printf statement, and thus using a sim_printf() in a path executing instructions wouldn't really make sense...

Step back from this somewhat tangent discussion to what you're trying to do to handle extended information display when your simulator stops execution.  My suggestion to define a command which displays your desired stuff would involve:

```
CTAB pats_cmd[] = {
  { "SHOWGREATSTUFF", &pats_greatstuff_output, 0, "SHOW great stuff" },
  { NULL, NULL, 0, NULL }
};

```

**Comment by markpizz** [comment]
Oops.  Ignore that it got sent before complete.

**Comment by markpizz** [comment]
There is a fundamental distinction between the simulator's console device and the session which initiates the simulator's execution. sim_printf() and the rest of SCP directly interacts with the session that initiates the simulator's execution and correctly does so during various configuration activities simulators support to configure, and customize the details of the setup and operation of the simulator and it's devices. These are appropriate in device attach routines, and MTAB action routines.

The simulator's console device defaults to coincide with the session that initiates the simulator's execution, but is operationally distinct and can readily be attached to a telnet session or serial port which then is completely independent of interactions in the session that initiates (and controls) the simulator's execution.

You ask:

Which specific APIs should be used to write to the console when the simulator is running? sim_putchar?

I'm not familiar with the specifics of operation of your favorite simulator (AltairZ80), so I can't say whether the distinction I described above between the session that initiates and controls the simulator execution is separate from a console device which the simulated system may (or may not) have. Most other simulators have such a distinction. The console device is an I/O device that exists in the simulated system and instructions (via various means) running in the simulator can do I/O to this device. Given this lack of knowing about the console vs session distinction, I can't reasonably answer your question. The comment before the sim_printf() API specifically refers to SCP provided features that relate to the session that initiated the simulation and absolutely nothing about the device which implements the console port of a system. Think about this: in general, most simulated CPU's don't have an instruction which translates to the equivalent of a printf statement, and thus using a sim_printf() in a path executing instructions wouldn't really make sense...

Step back from this somewhat tangent discussion to what you're trying to do to handle extended information display when your simulator stops execution. My suggestion to define a command which displays your desired stuff would involve:

```
CTAB pats_cmd[] = {
  { "SHOWGREATSTUFF", &pats_greatstuff_output, 0, "SHOW great stuff" },
  { NULL, NULL, 0, NULL }
};

static  t_stat pats_greatstuff_output(int32 arg, CONST char *buf)
{
sim_printf ("all sorts of great stuff\n");
sim_printf ("even more great stuff\n");
return SCPE_OK;
}

In the cpu_reset routine you have a line:
sim_vm_cmd = pats_cmd;
```

This combined with the previously mentioned which could be in a ~/simh.ini file:
```
sim> set cpu on
sim> ON ERROR SHOWGREATSTUFF %STATUS%
```
Will get normal STEP and STOP output along with any great stuff you want to print out. The numeric status value will be passed as a string to the pats_greatstuff_output routine which can be interpreted (or ignored) however you want.

**Comment by deltecent** [comment]
You win.

**Comment by markpizz** [comment]
None of this was anything about a contest that needed to be won.  My pitch was all about leveraging existing capabilities to achieve essentially what you were trying to do without mixing the functional barriers that exist in the SCP framework.

Folks have come along any number of times with changes they thought they needed from SCP and almost always there was another way to do it, or if it involved something that with some extensions ended up adding real functionality in SCP.
