### ISSUE TITLE
Stop modifying user .DSK images unconditionally (until a better solution found)

### ISSUE THREAD

**Issue by al20878** [open-simh/simh#13]
`.DSK` files may not be modified by simh without an explicit user consent.  Suggested it to freeze the modifications by applying the following temporary patch until a further (better) solution is found / suggested.  With the patch applied, the images, which have been tainted with, will still be able to provide `DISKINFO`, and do a potential `ZAP` (to remove the "footer"), but no further additions of the extraneous sector (the "footer") will be made.  Also, most (if not all) functionality is going to keep working (including the infamous autosize).  I've been running my systems with this patch for a long time now, since discovering the behind-the-scene modification by simh (and reporting it as an issue 1059 in the former source code repository).

```
From 15d77b6da98b3ae6721a97902f1a50241c6bf6fe Mon Sep 17 00:00:00 2001
From: Tony Lawrence <al20878@gmail.com>
Date: Tue, 14 Jun 2022 15:40:54 -0400
Subject: [PATCH 1/2] Disable DSK footer unconditionally

---
 sim_disk.c | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/sim_disk.c b/sim_disk.c
index d19cf034..0355f79f 100644
--- a/sim_disk.c
+++ b/sim_disk.c
@@ -2439,6 +2439,8 @@ time_t now = time (NULL);
 t_offset total_sectors;
 t_offset highwater;

+return SCPE_OK;
+
 if ((dptr = find_dev_from_unit (uptr)) == NULL)
     return SCPE_NOATT;
 if (uptr->flags & UNIT_RO)
--
2.33.0
```

**Comment by markpizz** [comment]
The effects of this suggested change are completely achieved by the execution of a "SET NOAUTOSIZE" command somewhere in the active configuration file prior to disk attaches.  If a user wants this always to be the case for ALL executions of the simulator, this command can appear in a separate file named simh.ini located in the user's HOME directory.  The separate simh.ini file is executed on every simulator startup, so the user will always have this behavior.

There is now significantly updated sim_disk functionality which more robustly honors reasonable behavior for disk containers both with and without metadata.  This functionality is available to everyone who doesn't "need" to implement the above mentioned change to sim_disk.c.  It is available at the head of the master branch of https://github.com/simh/simh.  Updated windows binaries are now available at https://github.com/simh/Win32-Development-Binaries.

A perfect example of a smart guy who knows a lot about many things, but not so much about some potential issues in earlier simh versions is visible at: https://github.com/wfjm/w11/issues/30  His issues which weren't reported in the https://github.com/simh/simh/issue system have now been addressed by changes recently made in the above mentioned updates.

Key changes which are now available in https://github.com/simh/simh, but not in https://github.com/open-simh/simh are mentioned in the README.md at https://github.com/simh/simh.

Everyone is free to use the code in the master branch at https://github.com/simh/simh as long as they don't need to make changes like the above one.

Feedback and bugs should be reported at https://github.com/simh/simh/issues.

I plan on working through the existing, 109 as yet unresolved issues in that repo and any new ones which crop up there or on the https://github.com/open-simh/simh/issues system.

**Comment by al20878** [comment]
@markpizz please stop pitching in on this issue here: we all heard what you've got to say previously.

User data may not be modified by the simulator, ever.  So if the chance exists (as with missing the mentioned setting), it has to be prevented, which the patch is aimed to do.  So no accidental "additions" would go into the user data -- never.  Period.

**Comment by pkoning2** [comment]
Anthony, it's ok for Mark to have his opinion and to state it; I don't think it is necessary to shut him down.  But we'll consider this PR.

**Comment by pkoning2** [comment]
Thanks Anthony, that's fine.

**Comment by Rhialto** [comment]
My personal preference would be to have this "SET NOAUTOSIZE" as a default built in, and people can turn it on if they want.

As a next step, it could be explored if the positive effects from the setting can be had without the negative ones, in some way or another.

**Comment by al20878** [comment]
Thank you @Rhialto for your input!  That was my first thought as well, but then I realized that:

1. Such `NOAUTOSIZE` would prohibit the logic of attaching undersized containers (which leads way back to the 3.x behavior);
2. While having turned it on, would cause the image to still get modified -- which is **the unacceptable behavior**.
 
So these two things are orthogonal, just because the metadata should not be mixed into the user data; not because there is some logic of the computation of a suitable device size.

**Comment by wfjm** [comment]
I really wonder a bit why the infamous meta-data feature isn't simply removed.  
The _pros_ have been stated many time, no need to repeat them here.  
Using `NOAUTOSIZE` to bypass an offensive and unacceptable feature isn't a solution, as @al20878 pointed out.  
I had for historical reasons some undersized containers, and have now to cleanup the mess.
Is there any credible argument of having meta-data appended to the container ?  
Would removing the  meta-data feature break something ?

**Comment by rms47** [comment]
As everyone has said, this issue has been litigated for a long time and, indeed, was one of the breaking points that led to Open-SimH.

My preferred solution for any compatibility-breaking new feature is to put it under a global option switch, for which the default setting is OFF (i.e., old behavior). Then, anyone who likes the new feature, compatibility break and all, can enable it in the .ini file.  But I will support the group consensus. This is not a V3.X issue.

**Comment by pkoning2** [comment]
I agree.  Would you care to create a PR to implement this behavior?

**Comment by markpizz** [comment]
The point of having the function in place/enabled by default is that folks who are most likely to benefit from it are those who are new to the simh world and would have to dig far deeper than most folks care to do to realize they would need it.


There already is a mechanism to globally disable this functionality.  Anyone desires that can easily disable it for themselves and their friends with a simh.ini file in their login directory that contains a line:
```
SET NOAUTOSIZE
```

Even experts who one would presume absolutely know exactly what they're doing might sometimes stumble along with an incorrect configuration which would be detected or accomodated by the feature.  An example of this is @wfjm's unintentionally having an RL device configured as a RL01 drive and attaching a RL02 disk image to the drive.  He was using a v3 simulator forever and never was aware of this error.  Things happened to work in his case since the RL02 disk image happened to have a RT11 file system on it in an RL01 sized partition at the beginning of the disk.  Look at the detailed analysis at: https://github.com/wfjm/w11/issues/30 to back up what I'm saying here.

If someone were to inadvertently forget to disable this feature and a disk container file was then changed, that change can be completely reversed by using the ZAP command on the affected container.

**Comment by pkoning2** [comment]
There are a number of problems with the existing code.
1. It isn't documented.
2. It modifies container files in a way previously not done, which affects other programs that look at container files.  For example, flx (the RSTS file system utility) does not correctly report the disk type for these modified containers because their length does not match that of any known DEC disk.

Thinking about it right now, I'm also troubled by the naming conflict between the much earlier autosize feature associated with various disk types, and this new thing that controls appending extra data.  Does it also disable the real autosize feature?

**Comment by markpizz** [comment]
> 1. It isn't documented.

What type of documentation would you be looking for? 

sim> HELP DISKINFO

> 2. It modifies container files in a way previously not done, which affects other programs that look at container files. For example, flx (the RSTS file system utility) does not correctly report the disk type for these modified containers because their length does not match that of any known DEC disk.

There are essentially 3 solutions to this:

1) sim> SET NOAUTOSIZE
2) sim> ZAP container-file
3) Check the PR request just submitted to the simtools repo which enhances the flx (rsts file system utility) to tolerate (ignore) simh disk metadata present in container files and properly determine the size of the data portion of the container.

Digging through rstsflx code and I can't find a code path that specifically cares about the disk type when referencing a container that already exists.

------

As for autosize, that is a feature added to the v4 codebase when disk containers were always created to be full simulated device sized.  Folks with working configurations have always had explicit (or default) device types for the relevant disks.

**Comment by al20878** [comment]
Let me say this again and again that "UNDOING something" is NOT the same as "NOT DOING something".

Modifying a .DSK file from outside the guest operating system is unacceptable practice, in general.  Even if the OS did not modify the file, and it was "accidentally" tainted with SimH and then "undone", the file may NOT end up being the same.  So it's irreversible, in general.

As such, this option of labeling must be a choice of the user, not a default action.

**Comment by mike632t** [comment]
What is the current state of this issue?

Is the _default_ behaviour now not to modify the disk or is the meta data still being inserted by default..

**Comment by pkoning2** [comment]
It hasn't changed yet.

**Comment by wfjm** [comment]
This status is a bit surprising, considering the whole history of the open-simh fork. Some issues are being worked on intensively, but the issue that caused all the commotion is not being addressed.

**Comment by al20878** [comment]
Just to post an update as for the _current_ behavior when `SET NOAUTOSIZE` is used (this is the first command in my `~/simh.ini` file):

- When attaching an existing disk container, for "footer" does not get appended;
- When a new image is created by the "attach" command, the pesky "footer" gets added.

So the `SET NOAUTOSIZE` command does not "globally" disable the feature...

**Comment by pkoning2** [comment]
The right answer is to remove this machinery.  It's just a case of someone having to get around to it.

**Comment by al20878** [comment]
> The right answer is to remove this machinery.

I already suggested a patch to at least disable adding the footers, for the time being.
```
--- a/sim_disk.c
+++ b/sim_disk.c
@@ -2439,6 +2439,8 @@ time_t now = time (NULL);
 t_offset total_sectors;
 t_offset highwater;

+return SCPE_OK;
+
 if ((dptr = find_dev_from_unit (uptr)) == NULL)
     return SCPE_NOATT;
 if (uptr->flags & UNIT_RO)
@@ -2502,6 +2504,8 @@ t_offset total_sectors;
 t_offset highwater;
 t_offset footer_highwater;

+return SCPE_OK;
+
 if ((dptr = find_dev_from_unit (uptr)) == NULL)
     return SCPE_NOATT;
 if (uptr->flags & UNIT_RO)
```
I can submit this patch as a PR anytime.

Since `sim_disk.c` seems to operate with some "assumptions" of the footer in place (or at least, in memory), the complete cleanup of the functionality may not be as simple (and may require deeper code changes).  But at least the above patch disables any unwanted changes to the actual containers -- i.e. changes not caused directly by the simulated software.

**Comment by GabrielRavier** [comment]
I must admit to also being a bit surprised by the absence of action on this for the past year - it seemed to me as though a general consensus had been reached that this was in fact an issue which should be fixed (with the notable exception of Mr. Pizzolato, who has sadly taken distressingly drastic action to enforce his opinion on the issue).

Though perhaps it is simply a small enough issue that people who have encountered it have just decided to work around it, or have found it too complicated for now to get a "clean" fix in, or have found themselves diverted from working on a fix for this issue for any number of possible reasons - I've seen similar issues being unfixed for an unbelievable amount of time before (see also e.g. the 18-year lasting GTK file picker thumbnail issue).

**Comment by pkoning2** [comment]
There's been discussion but there are several possible approaches.  One is what was suggested above.  Another is to remove the trailer code entirely, and have people use a tool to strip any files that have it.  (I should merge the long-pending PR in simtools that adds such a tool.)  The third is to make the disk code match what is in V3.
The right answer is to do something, just to get past this inaction.  @al20878 could you make a PR for your change?

**Comment by pkoning2** [comment]
Thanks for the PR, it's been merged.  That closes this issue though as I mentioned there still is opportunity for further cleanup.
