### ISSUE TITLE
SCP: SET ON in init scripts not working as described

### ISSUE THREAD

**Issue by deltecent** [open-simh/simh#130]
> The values following the word "ON" are specific error codes (SCPE_xxxx) text or numeric values for xxxx. If your driving script otherwise doesn't deal with error trapping, then the general word ERROR covers everything:
> ```
> sim> # enable error trapping:
> sim> SET ON 
> sim> # trap all non 0 values
> sim> ON ERROR Echo %STATUS%-%TSTATUS%
> sim> # specifically for your extended command passing status in case it is interesting...
> sim> ON ERROR <your-extended-command> %STATUS%
> ```
> You wouldn't have to type the above except once into an init file: ~/simh.ini

I have a ~/simh.ini file that contains:

```
set on
on error reg
```

When I run `altairz80` I get the following:

```
% altairz80 -v

Altair 8800 (Z80) simulator V4.0-0 Current        git commit id: a06ab205
/Users/patrick/simh.ini-2> set on
/Users/patrick/simh.ini-3> on error reg
sim> show on
On Processing for input commands is disabled

sim>
```

I have to run altairz80 with the -o switch in order for my ON settings in ~/simh.ini to remain active.

```
% altairz80 -v -o

Altair 8800 (Z80) simulator V4.0-0 Current        git commit id: a06ab205
/Users/patrick/simh.ini-2> set on
/Users/patrick/simh.ini-3> on error reg
sim> show on
On Processing for input commands is enabled
    on ERROR     reg

on state and actions are inherited by nested do commands and subroutines
sim>
```

Is ~/simh.ini supposed to require inheritance with -o?

I have the same issue when using ./altairz80.ini

**Comment by markpizz** [comment]
Oops.  My advice was a little off.

On actions default to only affect activities within a running command file since many cases ALL commands run in that command file and a user never sees a sim> prompt.

For your interactive use in either file ~/simh.ini or ./altair.ini file you should be able to:
```
set on inherit
on error reg
```
Or, as you've otherwise discovered, invoking the simulator with -O enables INHERITance globally.

I'll update the HELP information to describe the INHERIT and NOINHERIT options on the SET ON command.

**Comment by deltecent** [comment]
I suspected that's what was going on, but I wanted to make sure. Thanks.

**Comment by deltecent** [comment]
Can you show me what I'm still doing wrong? Both `~/simh.ini` and `cpm.sim` both lose the `ON ERROR` when escaping out of the simulator started with a command file. I'm suspecting the inheritance only works for children, not parents, meaning there's no way to enable `-o` from a command file and `-o` must be used from the command line.

```
# ~/simh.ini
SET ON INHERIT
SHOW ON
```

```
# ./cpm.sim
set cpu z80
;dep clock 2000
set throttle 300k
set sio nosleep
on error reg
attach dsk0 cpm63k.dsk
load dbl.bin ff00
show on
go ff00
```

```
% altairz80 -v cpm.sim   

Altair 8800 (Z80) simulator V4.0-0 Current        git commit id: a06ab205
/Users/patrick/simh.ini-1> SET ON INHERIT
/Users/patrick/simh.ini-2> SHOW ON
On Processing for input commands is disabled

on state and actions are inherited by nested do commands and subroutines
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-1> set cpu z80
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-1> ;dep clock 2000
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-3> set throttle 300k
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-4> set sio nosleep
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-5> on error reg
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-6> attach dsk0 cpm63k.dsk
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-7> attach dsk1 ../../modem7/modem7.dsk
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-8> load dbl.bin ff00
256 bytes [1 page] loaded at ff00.
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-9> show on
On Processing at Do Nest Level: 1 is disabled
    on ERROR     reg

on state and actions are inherited by nested do commands and subroutines
/Users/patrick/Library/Mobile Documents/com~apple~CloudDocs/AltairGIT/cpm22/88-DCDD/cpm.sim-10> go ff00


63K CP/M
Version 2.2mits (07/28/80)
Copyright 1980 by Burcon Inc.

A>
Simulation stopped, PC: 0FA69 (IN A,(10h))
sim> show on
On Processing for input commands is disabled

on state and actions are inherited by nested do commands and subroutines
sim>
```

**Comment by markpizz** [comment]
Hi Patrick,

I screwed up again.

There are three commands you'll need to enter in the simh.ini:
```
# Enable ON trapping
set on
# Enable default error trap to invoke REG command
on error reg
# Enable ON inheritance for subsequent/nested DO command files
set on inherit
```

The SET ON command enables trapping with the initial default trap of ON ERROR RETURN if no ON xxx SOMECMD commands haven't already been entered.
The SET NOON disables error trapping which you might want to do for one or more commands which may or may not return an error status which you don't care about.  You can subsequently reenable ON trapping with SET ON which will then leverage whatever ON xxx WHATEVER traps you may have defined.

The SET ON INHERIT or SET ON NOINHERIT merely enable or disable the inheritance state without regard to whatever trap may currently be enabled (or not).

I will update the PR that revises the HELP command output to explain this clearly.

**Comment by deltecent** [comment]
That seems to do the trick!
