### ISSUE TITLE
SCP: Discussion about adding a -q flag to "ON" command

### ISSUE THREAD

**Issue by deltecent** [open-simh/simh#136]
When using the ON command, the standard stop message is displayed before the ON command is processed.

```
sim> set on
sim> on stop ex 0
sim> on step ex af
sim> g

Simulation stopped, PC: 05C10 (ANI 02h)
0:	00
sim> s

Step expired, PC: 05C12 (JNZ 5C0Eh)
AF:	0210
sim> 
```

Sometimes this information isn't wanted and takes screen space away from the desired output.

I have some code that adds a -q (quiet) switch to "ON":

```
sim> set on
sim> on -q stop echof -n "%TSTATUS% ";ex 0
sim> on -q step echof -n "%TSTATUS% ";ex af
sim> g
Simulation stopped 0:	00
sim> s
Step expired AF:	0210
sim> 
```

This puts all the desired output on 1 line instead of 3, which I've found helpful when single-stepping a lot of code, and adds quite a bit of flexibility to the ON command without impacting anyone not having any use for ON switches.

The SHOW ON command has another column added to the list to indicate if the switch is set for that stop code. If global ON ERROR is set, specific codes use their switch setting while unlisted codes use ERROR's switch setting.

```
sim> on 1 ex 100
sim> show on
On Processing for input commands is enabled
    on 1               ex 100
    on STEP    QUIET   echof -n "%TSTATUS% ";ex af
    on STOP    QUIET   echof -n "%TSTATUS% ";ex 0
 
sim> set break 0
sim> g 0

Breakpoint, PC: 00000 (NOP)
100:	00
sim>
```
The code I've written will support future ON switches as well.
 
Before I push a PR, I wanted to run the idea by the SCP group.

**Comment by deltecent** [comment]
Of course it's already in there! I couldn't find it in the help, but I did just find it in the source comments.

It's like trying to build a house out of Lego. I just need to find the right pieces.

**Comment by markpizz** [comment]
Thanks for asking before putting out a PR.  

Asking questions before jumping to change code locally as you did in this case might be even easier, but possibly not as fun. :-)

**Comment by deltecent** [comment]
I think I have it working the way I want with the alternative methods:
```
; ~/simh.ini
SET ON
ON STOP ECHOF -n "\n%TSTATUS% ";REG
ON STEP ECHOF -n "%TSTATUS% ";REG
ON 1 ECHOF -n "%TSTATUS% ";REG
ON 2 ECHOF -n "%TSTATUS% ";REG
ON 3 ECHOF -n "%TSTATUS% ";REG
ON 4 ECHOF -n "%TSTATUS% ";REG
ON 5 ECHOF -n "%TSTATUS% ";REG
SET ON INHERIT

set env s=s -q
set env g=g -q
set env c=c -q
set env boot=boot -q
```
