### ISSUE TITLE
IBM1130:  Can't "attach cr <filename>"

### ISSUE THREAD

**Issue by Jim-F** [open-simh/simh#138]
I traced this problem to a line in cr_attach()
(file ibm1130cr.c) that seems to be treating a
pointer rather sketchily.

Yes, this is an ancient file, and has apparently worked as
expected lo these many years, but it would appear that gcc 12.2.0
is not treating this pointer operation the same way gcc has
in the past (and the way the file's author intended).

I fixed the problem by making the minimum possible change
to the code, but I would think there's no need for the
sizeof() at all -- surely MAXARGLEN+1 from the earlier
declaration of list_save would suffice as the length
argument for the strlcpy().  I'll leave that to the judgment
of whoever might undertake to commit a change to
this file.

NOTE: Yes, I know I build SimH unconventionally, with
MinGW64 and static linking (except for PCAP), but I've
been doing that for years with no problems, and in
fact I made a new PDP-11, several VAX models, and
a PDP-10KL at the same time as the 1130, and they
run their respective operating systems (various
flavors of RSX-11 and RSTS, various flavors of
VMS, and "Panda" TOPS-20) with no problems.
No, I have not tried to reproduce the IBM 1130 problem with
a MinGW 32-bit toolchain or with Microsoft Visual Studio.

NOTE_1:  I built everything with HAVE_EDITLINE this time,
and with the static linking, libreadline.a wants
libncurses.a, and the latter apparently has a couple
of multiple definitions among its own object components.
Hence the "-Wl,--allow-multiple-definition".  Looks
scary, I know, but presumably harmless.

Build:

![1_build](https://user-images.githubusercontent.com/17226010/205141516-b4e518cb-98e2-491f-9fcb-f965782b4f57.jpg)

Version:

![2_version](https://user-images.githubusercontent.com/17226010/205141555-0ebb2759-b00a-49ea-add4-bb19320eef2f.jpg)

Not OK:

![3_not_ok](https://user-images.githubusercontent.com/17226010/205141588-0fdccdcb-61cc-4fa0-ac95-aec1ce59dcba.jpg)

Code change:

![4_code_change](https://user-images.githubusercontent.com/17226010/205141608-bc8fc1ea-6d82-4911-bb7a-8527501ff72f.jpg)

OK:

![5_ok](https://user-images.githubusercontent.com/17226010/205141632-c4c50caa-91a3-4950-9ef8-0569cb4435f7.jpg)

**Comment by pkoning2** [comment]
Funny that would ever have worked, because clearly the original code translates to `sizeof(char)` which equally clearly is not what was intended here.  If old compilers made this "work" then those old compilers were handling things incorrectly, and very surprisingly so.
Looks good.  Can you submit a PR for this?

**Comment by Jim-F** [comment]
>  Looks good. Can you submit a PR for this?

Do you have any aesthetic preference about the fix?  I.e., just leave
what I did (sans the #if0...#else..#endif), or just use MAXARGLEN+1,
or. . .?

**Comment by Jim-F** [comment]
> Can you submit a PR for this?

If you mean a pull request (which entails, I gather, creating a branch),
surely I don't have permission to do this?   In the past, it's always been
Mark Pizzolato who has handled the actual Github business when I've
submitted changes to him (for the, ahem, "other" V4 SimH).

I've never actually done that sort of thing myself, and reading the Github
docs suggests I'd have to be granted some permissions by the repository
administrator (which I am **not** asking for!  ;->  ).

**Comment by pkoning2** [comment]
The fix should replace the wrong line by the correct line.  No `#if 0` stuff.
As for pull requests, I guess we should document that better.  The procedure works this way:
1. Ask Github to fork this repository -- which in effect makes a private copy that is related to the original.
2. Check out that fork.  Make the change, push it back to Github.
3. In Github, look at your fork.  It will show that it is 1 commit ahead of open-simh/simh.  Click "contribute" to create the pull request.
That's it.  You can keep using the fork for more work, but before you do, tell Github to "sync" it with the original, and then "git pull" on your workstation to bring in the current simh state.
