### ISSUE TITLE
simh not compiling on Android

### ISSUE THREAD

**Issue by vaxorcist** [open-simh/simh#155]
/simh $ make vax780

lib paths are: /usr/lib /data/data/com.termux/files/usr/lib /system/lib
include paths are:  /data/data/com.termux/files/usr/lib/clang/15.0.6/include /data/data/com.termux/files/usr/include/arm-linux-androideabi /data/data/com.termux/files/usr/include
using libm: /system/lib/libm.so
using librt: /data/data/com.termux/files/usr/lib/librt.so
using libpthread: /data/data/com.termux/files/usr/lib/libpthread.so /data/data/com.termux/files/usr/include/pthread.h
using libpcre: /data/data/com.termux/files/usr/lib/libpcre.so /data/data/com.termux/files/usr/include/pcre.h
using semaphore: /data/data/com.termux/files/usr/include/semaphore.h
using libdl: /system/lib/libdl.so /data/data/com.termux/files/usr/include/dlfcn.h
*** Warning ***
*** Warning *** vax780 Simulator is being built WITHOUT
*** Warning *** libpcap networking support
*** Warning ***
*** Warning *** To build simulator(s) with libpcap networking support you
*** Warning *** should install the libpcap development components for
*** Warning *** for your Linux system:
*** Warning ***        $ sudo apt-get install libpcap-dev
*** Warning ***
*** Info ***
*** Info *** Simulators on your Linux platform can also be built with
*** Info *** extended LAN Ethernet networking support by using VDE Ethernet.
*** Info ***
*** Info *** To build simulator(s) with extended networking support you
*** Info *** should install the vde2 package to provide this
*** Info *** functionality for your Linux system:
*** Info ***        $ sudo apt-get install vde2
*** Info ***
***
*** vax780 Simulator being built with:
*** - compiler optimizations and no debugging support. clang version 15.0.6.
*** - Local LAN packet transports: TAP NAT(SLiRP)
*** - Per simulator tests will be run.
***
*** git commit id is ce791138b5b5365105415a9a1cf4091d6e50a43d.
*** git commit time is 2022-12-02T13:19:56+0100.
***
In file included from <built-in>:387:
<command line>:7:9: error: '__ANDROID_API__' macro redefined [-Werror,-Wmacro-redefined]
#define __ANDROID_API__ 31
        ^
<built-in>:381:9: note: previous definition is here
#define __ANDROID_API__ __ANDROID_MIN_SDK_VERSION__
        ^
1 error generated.
make: *** [makefile:2175: BIN/buildtools/BuildROMs] Error 1
/simh $ uname -a
Linux localhost 4.14.186-24638760 #1 SMP PREEMPT Sat Oct 1 13:01:13 KST 2022 armv8l Android

**Comment by markpizz** [comment]
The definition for the ANDROID_API stuff seems to vary depending on which termux is installed and on the host Android environment.

Try:
```
make vax780 WARNINGS=ALLOWED
```

This works on my phone, I can't get a working termux environment on my relatively recent Samsung tablet.

**Comment by vaxorcist** [comment]
Hi,

make vax780 WARNINGS=ALLOWED

worked perfectly for me.

I've got Android 12 here on a Samsung Galaxy A13 with termux V118.
You must have all files on the internal storage otherwise you get no
permissions.

Thanks for your help!

Mark Pizzolato ***@***.***> schrieb am Mi., 28. Dez. 2022,
20:11:
