### ISSUE TITLE
Unintended use of REG_UNIT flag in KX10 source modules

### ISSUE THREAD

**Issue by markpizz** [open-simh/simh#16]
I'm in the process of merging the simh v3.12 codebase into v4.  This includes changes by J. David Bryan which significantly cleaned up simh REGister code and redefined the relevant initializing macros.

The REG_UNIT flag was never intended to be explicitly mentioned in simulator code.  It was a flag that was buried inside of the URDATA macro.  In general the use of this macro (and thus the internally used flag) was to describe a field in a device's UNIT structure which is actually an array of values present in each of the DEVICE's units.  For example, in kx10_dt.c we've currently got:
```
    { URDATA (POS, dt_unit[0].pos, 10, T_ADDR_W, 0,
              DT_NUMDR, PV_LEFT | REG_RO | REG_UNIT) },
```
In prior versions, since the URDATA macro specifically adds the REG_UNIT under the covers, explicitly stating it as part of the flags bits in the URDATA macro is outside of the intended use.

Likewise, since REG_UNIT is supposed to be an under the covers flag bit, it should not be present in any other REGister declaration.  The cases:
```
./PDP10/kx10_lp.c(93):    { DRDATA (STATUS, lpt_unit.STATUS, 18), PV_LEFT | REG_UNIT },
./PDP10/kx10_lp.c(94):    { DRDATA (TIME, lpt_unit.wait, 24), PV_LEFT | REG_UNIT },
./PDP10/kx10_pt.c(80):    { DRDATA (STATUS, ptp_unit.STATUS, 18), PV_LEFT | REG_UNIT},
./PDP10/kx10_pt.c(81):    { DRDATA (TIME, ptp_unit.wait, 24), PV_LEFT | REG_UNIT},
./PDP10/kx10_pt.c(104):    { DRDATA (STATUS, ptr_unit.STATUS, 18), PV_LEFT | REG_UNIT},
./PDP10/kx10_pt.c(105):    { DRDATA (TIME, ptr_unit.wait, 24), PV_LEFT | REG_UNIT},
 ```
Each are actually using the REG_UNIT flag in an unintended way, since although each of these cases do refer to some field in a UNIT structure, there is only a single UNIT in each of these DEVICEs, so the intended 'array' isn't really there.

REG_UNIT is not defined in simh v3.12 anymore since there now is general support for REGisters which describe a field in an array of structures, the UNIT is just a special case of that support and the URDATA macro is defined accordingly.

If REG_UNIT was used in more than these 7 cases, it might be appropriate to define it as 0, but that's really not needed.  Each of these "| REG_UNIT" string instances can be removed right now before the merged v3.12 REG changes are part of a PR.

**Comment by rcornwell** [comment]
How do you specify the same thing with URDATA?

**Comment by markpizz** [comment]
The URDATA macro (in prior versions) appended REG_UNIT to the flags internally so that the various operations on REGisters could distinguish that special case.  This is generalized with structure support going forward.  There are MANY MANY uses of URDATA in all the simulator code and no other mentions anywhere of REG_UNIT.

Just remove the 7 occurances of "| REG_UNIT" and things will be clean with unchanged behavior and then not notice when REG_UNIT is removed.

**Comment by rcornwell** [comment]
Looking at SCP source I don't see this as an issue. REG_UNIT means that the register is in the unit structure. Which is where these items are.

**Comment by markpizz** [comment]
Please search for REG_UNIT in ALL of the source for ALL simulators.  The ONLY 7 instances where they appear in simulator code are mentioned above in the KX10 source modules.

The REG_UNIT flag was/is intended to be used **INTERNALLY** within SCP to provide a way to have the same field in a UNIT structure represent an array (within a DEVICE's set of UNITS).  Historically it is added to the flags REG field by the URDATA macro to convey this detail to SCP.  Search for URDATA in all the source modules, and you will find that the ONLY instance where the call to the URDATA macro passes REG_UNIT is in kx10_dt.c.  The simh.doc did mention the REG_UNIT flag, but as I've tried to explain here, it's intended use was completely under the covers and not directly intended to appear in simulator code.

If you remove the 7 instances, you will notice that NOTHING breaks.  You get the same working REGisters.

The merged 3.12 register functionality removes the REG_UNIT declaration and thus the simulators which references the above mentioned source modules will then fail to compile.

**Comment by markpizz** [comment]
If you use the URDATA macro which takes as an argument the depth of the array'd REGister it defines, then it will work just fine.  

Your use of REG_UNIT in the pt and lp devices with the DRDATA macro is absolutely never how it was intended and serves no specific purpose now.  Adding more units to these devices will not suddenly create an array register since the DRDATA macro doesn't take a depth parameter and is explicitly unaware of how many units the device has.

If you first test WITHOUT the REG_UNIT in the current code you will see no change.

I'll create a PR with the merged code when all the existing simulators in the codebase compile without error.  You can test the PR code at that time and block its merge if you see problems.

**Comment by markpizz** [comment]
> Why is this not noted as being for internal use only? 

That detail slipped through the cracks.  The writing a simulator document going back to simh v3.8-1 (http://simh.trailing-edge.com/docs/simh.pdf) specifically says:
```
Finally, macro URDATA defines an arrayed register whose data is part of the UNIT structure. This macro
must be used with great care. If the fields are set up wrong, or the data is actually kept somewhere else,
storing through this register declaration can trample over memory. The macro is invoked by:

      URDATA (name, location, radix, width, offset, depth, flags)

The location should be an offset in the UNIT structure for unit 0. The width should be 32 for an int32 or
uint32 field, and T_ADDR_W for a t_addr filed. The flags can be any of the normal register flags;
REG_UNIT will be OR’d in automatically. For example, the following declares an arrayed register of all the
UNIT position fields in a device with 4 units:

      { URDATA (POS, dev_unit[0].pos, 8, T_ADDR_W, 0, 4, 0) } 
```

Like I said in the subject of this issue and in my efforts to explain, the intended use of the flag was internal to SCP.  The fact that in all of Bob's simulators and the many other simulators that have been written since, the only time REG_UNIT is explicitly mentioned in simulator code is the 7 places in the KX10 modules.  This fact, along with the fact that removing it from these modules will have no negative effects, suggests that you clearly don't believe me.  Please consult a higher authority on this subject @rms47

**Comment by rcornwell** [comment]
Removed REG_UNIT.
