### ISSUE TITLE
Abstract CPU implementation / ASAP3 - Centurion

### ISSUE THREAD

**Issue by fredcwbr** [open-simh/simh#166]
- #### Context  :: Guide request on abstract CPU coding 
-
- Educational proposal using simh as teaching tool on processor design 
- 
- Looking for a Guide/Tutorial on coding an  abstract CPU (similar to Malvino's SAP-3) in order to code the CENTURION CPU-6 on the simh from scratch . 
-

With the restoration of a Centurion Microcomputer by https://www.youtube.com/@UsagiElectric  and a group of people that reverse engineered almost all machine, it looks interesting to code it  on simh. 

Just found simh last week , and didn't quite figure how to code the SAP-3 , in order to tackle the CENTURION CPU-6 .,, 
using this as a learning tool to cpu design. 

- #### "sim> SHOW VERSION" 

 simulator V4.0-0 Current
    Simulator Framework Capabilities:
        32b data
        32b addresses
        no Ethernet
        Idle/Throttling support is available
        Virtual Hard Disk (VHD) support
        RAW disk and CD/DVD ROM support
        Asynchronous I/O support (Lock free asynchronous event queue)
        Asynchronous Clock support
        FrontPanel API Version 12
    Host Platform:
        Compiler: GCC 12.2.0
        Simulator Compiled as C arch: x64 (Release Build) on Jan 30 2023 at 17:59:22
        Build Tool: simh-makefile
        Memory Access: Little Endian
        Memory Pointer Size: 64 bits
        Large File (>2GB) support
        SDL Video support: No Video Support
        PCRE RegEx (Version 8.41 2017-07-05) support for EXPECT commands
        OS clock resolution: 1ms
        Time taken by msleep(1): 1ms
        OS: Linux alpha 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux
        tar tool: tar (GNU tar) 1.34
        curl tool: curl 7.87.0 (x86_64-pc-linux-gnu) libcurl/7.87.0 OpenSSL/3.0.7 zlib/1.2.13 brotli/1.0.9 zstd/1.5.2 libidn2/2.3.3 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.10.0 nghttp2/1.51.0 librtmp/2.3
        git commit id: 09899c18
        git commit time: 2023-01-22T13:55:58-0800

- #### Simulator  built on Debian 11 linux, with cmake  from git clone

**Comment by pkoning2** [comment]
Building a new simulator, whether the simulated machine is "real" or a paper model, sounds like a good project and SIMH should be a good way to do so.  For example, it would be an interesting idea to do a MIX simulator in SIMH.

I'm not sure what you're looking for in this "issue".  Is there a problem with SIMH that stands in the way?  Or are you looking for help from the community in your project of building a new simulator?  If the latter, it will be more effective to use the mailing list (simh@groups.io) for that.

**Comment by fredcwbr** [comment]
> 

I'm looking for help on building the simulator for both the ASAP-3  (in order to learn the basics) , and finally the Centurio CPU-6.,

**Comment by fredcwbr** [comment]
Just a follow-up to whomever is taking care of "Help With SimH" web page, the Topid SimH users mailing list states:  (SimH AT trailing-edge DOT com)., but for some reason this  email does not work properly.  Using the simh AT groups DOT io , as suggested by pkoning2 above, did the trick .
Thanks for the assistance., 

Moving my much needed help  to proper channel.

Best regards., 
..

Fred
