### ISSUE TITLE
Git/GitHub: LF or CRLF

### ISSUE THREAD

**Issue by deltecent** [open-simh/simh#183]
I am having one heck of a time with Git on my Mac.

My diffs end up looking like this:

```
-#define EVENT_REDRAW     1                              /* redraw event for SDL */
-#define EVENT_CLOSE      2                              /* close event for SDL */
-#define EVENT_CURSOR     3                              /* new cursor for SDL */
-#define EVENT_WARP       4                              /* warp mouse position for SDL */
-#define EVENT_DRAW       5                              /* draw/blit region for SDL */
-#define EVENT_SHOW       6                              /* show SDL capabilities */
-#define EVENT_OPEN       7                              /* vid_open request */
-#define EVENT_EXIT       8                              /* program exit */
-#define EVENT_SCREENSHOT 9                              /* produce screenshot of video window */
-#define EVENT_BEEP      10                              /* audio beep */
-#define MAX_EVENTS      20                              /* max events in queue */
+#define EVENT_REDRAW      1                              /* redraw event for SDL */^M
+#define EVENT_CLOSE       2                              /* close event for SDL */^M
+#define EVENT_CURSOR      3                              /* new cursor for SDL */^M
+#define EVENT_WARP        4                              /* warp mouse position for SDL */^M
+#define EVENT_DRAW        5                              /* draw/blit region for SDL */^M
+#define EVENT_SHOW        6                              /* show SDL capabilities */^M
+#define EVENT_OPEN        7                              /* vid_open request */^M
+#define EVENT_EXIT        8                              /* program exit */^M
+#define EVENT_SCREENSHOT  9                              /* produce screenshot of video window */^M
+#define EVENT_BEEP       10                              /* audio beep */^M
+#define EVENT_FULLSCREEN 11                              /* fullscreen */^M
+#define EVENT_SIZE       12                              /* set window size */^M
+#define MAX_EVENTS       20                              /* max events in queue */^M
 
 typedef struct {
     SIM_KEY_EVENT events[MAX_EVENTS];
@@ -515,7 +518,8 @@ SDL_SetHint (SDL_HINT_RENDER_DRIVER, "software");
 SDL_SetHint (SDL_HINT_VIDEO_ALLOW_SCREENSAVER, "1");
 #endif
 
-status = SDL_Init (SDL_INIT_VIDEO);
+//status = SDL_Init (SDL_INIT_VIDEO);^M
+status = SDL_Init (SDL_INIT_EVENTS);^M
```

What is with the `^M` at the end of my lines? I've messed around with Git's normalization, but this always seems to happen.

Is there anyone else using a Mac and how do you deal with this?

When I clone the repository, all the files end in CRLF. When I look at the files with a hex editor, the lines I add also end in CRLF, so I don't know what Git is complaining about.

**Comment by pkoning2** [comment]
I've been using a Mac for a very long time and haven't seen this.  Are you supplying your own diff command?  That may be the reason.  Try "git diff --no-ext-diff".
If that's not the answer, can you post the output from "git config -l"?

**Comment by deltecent** [comment]
```
 % git config -l                          
credential.helper=osxkeychain
init.defaultbranch=main
user.name=Patrick Linstruth
user.email=patrick@deltecent.com
core.autocrlf=false
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
remote.origin.url=git@github.com:deltecent/open-simh.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.upstream.url=https://github.com/open-simh/simh.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
```

**Comment by deltecent** [comment]
This is a hex dump of `.gitattributes`:

```
% xxd .gitattributes 
00000000: 2a2e 6a70 6720 6269 6e61 7279 0d0a 2a2e  *.jpg binary..*.
00000010: 706e 6720 6269 6e61 7279 0d0a 2a2e 736c  png binary..*.sl
00000020: 6e20 6269 6e61 7279 0d0a 2a2e 7663 7072  n binary..*.vcpr
00000030: 6f6a 2062 696e 6172 790d 0a2a 2e65 7865  oj binary..*.exe
00000040: 2062 696e 6172 790d 0a2a 2e6c 6461 2062   binary..*.lda b
00000050: 696e 6172 790d 0a2a 2e62 696e 2062 696e  inary..*.bin bin
00000060: 6172 790d 0a2a 2e69 6d64 2062 696e 6172  ary..*.imd binar
00000070: 790d 0a2a 2e72 696d 2062 696e 6172 790d  y..*.rim binary.
00000080: 0a2a 2e74 6170 2062 696e 6172 790d 0a2a  .*.tap binary..*
00000090: 2e64 736b 2062 696e 6172 790d 0a2a 2e76  .dsk binary..*.v
000000a0: 6864 2062 696e 6172 790d 0a2a 2e63 7264  hd binary..*.crd
000000b0: 2062 696e 6172 790d 0a2a 2e64 636b 2062   binary..*.dck b
000000c0: 696e 6172 790d 0a73 696d 5f72 6576 2e68  inary..sim_rev.h
000000d0: 2065 7870 6f72 742d 7375 6273 740d 0a0d   export-subst...
000000e0: 0a
```
I added a space character at the end of `*.jpg binary`:
```
% xxd .gitattributes 
00000000: 2a2e 6a70 6720 6269 6e61 7279 200d 0a2a  *.jpg binary ..*
00000010: 2e70 6e67 2062 696e 6172 790d 0a2a 2e73  .png binary..*.s
00000020: 6c6e 2062 696e 6172 790d 0a2a 2e76 6370  ln binary..*.vcp
00000030: 726f 6a20 6269 6e61 7279 0d0a 2a2e 6578  roj binary..*.ex
00000040: 6520 6269 6e61 7279 0d0a 2a2e 6c64 6120  e binary..*.lda 
00000050: 6269 6e61 7279 0d0a 2a2e 6269 6e20 6269  binary..*.bin bi
00000060: 6e61 7279 0d0a 2a2e 696d 6420 6269 6e61  nary..*.imd bina
00000070: 7279 0d0a 2a2e 7269 6d20 6269 6e61 7279  ry..*.rim binary
00000080: 0d0a 2a2e 7461 7020 6269 6e61 7279 0d0a  ..*.tap binary..
00000090: 2a2e 6473 6b20 6269 6e61 7279 0d0a 2a2e  *.dsk binary..*.
000000a0: 7668 6420 6269 6e61 7279 0d0a 2a2e 6372  vhd binary..*.cr
000000b0: 6420 6269 6e61 7279 0d0a 2a2e 6463 6b20  d binary..*.dck 
000000c0: 6269 6e61 7279 0d0a 7369 6d5f 7265 762e  binary..sim_rev.
000000d0: 6820 6578 706f 7274 2d73 7562 7374 0d0a  h export-subst..
000000e0: 0d0a 
```
The hex dump shows the space added with the same CRLF line termination. Now `git diff` looks like this:
```
% git diff .gitattributes 
diff --git a/.gitattributes b/.gitattributes
index 63a2b0dc..932b1bb8 100644
--- a/.gitattributes
+++ b/.gitattributes
@@ -1,4 +1,4 @@
-*.jpg binary
+*.jpg binary ^M
 *.png binary
 *.sln binary
 *.vcproj binary
```
I don't know why `git diff` is showing 2 character changes when there's only 1.

**Comment by deltecent** [comment]
I don't know if this has any relevance:

[https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings](url)

**Comment by markpizz** [comment]
What you're seeing is a consequence of the historical project CRLF storage for line endings.  There really is no magic in .gitattributes that can keep the CRLF line endings for all the places it ever existed.  The .gitattributes text concept presumes that LF line endings exist in the repo and extractions and insertions convert to the host specific line endings.  Changing this would change essentially all files just for this purpose and would then break various recipes that expect CRLF line endings.

Your reference to:  [https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings](https://github.com/open-simh/simh/issues/url) is all about starting a project from scratch and having line endings behave reasonably across platforms.

**Comment by deltecent** [comment]
This seems to be the answer:
```git config --global core.whitespace cr-at-eol```

Always have to find the work-around for Windows. :)

**Comment by markpizz** [comment]
Looking at your initial message in this issue, it seems that you changed something about the lines between EVENT_REDRAW and MAX_EVENTS.  Maybe adding spaces.  Your complaining about the ^M at the end of the lines indicated in the diff and that's just how git diff reports changed lines when the repo stores lines with CRLF line endings.  There was no added ^M that wasn't supposed to be there, it just happens to be displayed, but it is also there in the original lines as well, just not displayed.

As for: 
```
git config --global core.whitespace cr-at-eol
```
if that merely suppresses the ^M at the end of lines displayed in git diff, then fine.  If it has any other effect related to storing data in the repo, then that should not be done!

**Comment by deltecent** [comment]
@markpizz do you provide your personal email address to people? I sometimes have questions I know you have the answer to.

**Comment by markpizz** [comment]
I have mentioned my email address numerous times in git issues.  It is mark@infocomm.com.

You could also find that in any message I've sent to the simh mailing list.  I found yours by doing the same.

**Comment by deltecent** [comment]
>Your complaining about the ^M at the end of the lines indicated in the diff and that's just how git diff reports changed lines when the repo stores lines with CRLF line endings.

The reason I brought it up is because once in the past, something like this happened and when I uploaded a PR, it thought a bunch of lines had changed when they hadn't and I didn't want that to happen again. Since this appears to be just a display issue, I'm not concerned. I just didn't want my PRs to change line endings as that would be bad.

**Comment by markpizz** [comment]
> > Your complaining about the ^M at the end of the lines indicated in the diff and that's just how git diff reports changed lines when the repo stores lines with CRLF line endings.
> 
> The reason I brought it up is because once in the past, something like this happened and when I uploaded a PR, it thought a bunch of lines had changed when they hadn't and I didn't want that to happen again. Since this appears to be just a display issue, I'm not concerned. I just didn't want my PRs to change line endings as that would be bad.

Well, depending on how you edited the modules involved, you could simply force all of any files you worked on (or created new) to consistently have the CRLF line endings with:

```
$ dos2unix *.c *.h
$ dos2unix *.c *.h
$ unix2dos *.c *.h
```

I'm doing the dos2unix twice to catch any odd mixed line endings that might have crept in depending on editing activities.  Doing a dos2unix on files which already have LF line endings doesn't change anything.

These steps will force everything to LF line endings and the force them back to CRLF line endings.  

dos2unix is available on macOS via brew.

**Comment by pkoning2** [comment]
The odd thing is that "git diff --no-ext-diff" does not display any ^M in the diffs for me.  That's on a Mac.  So I don't know why it would display that way for others.  My git is "2.37.1 (Apple Git-137.1)" if that matters.

**Comment by markpizz** [comment]
My Intel macMini has the same git version and is running macOS Monterey 12.6.3.

"git diff" shows ^M on pending changes to the simh repo.  It's a little hard to see the ^M due to rather harsh coloration in the macOS terminal window, by default it shows the ^M's as red in a black background.  I don't know how to change that, or really care either...  I get the same output with "git diff --no-ext-diff" as well.

**Comment by pkoning2** [comment]
Typically there are command switches to turn off color, but since I tend to forget them I use a simple hack: pipe the command output to "cat".  That doesn't change the contents (except for "ls" where it implies "-1") but it makes stdout be "not a terminal" so the color is disabled.

**Comment by deltecent** [comment]
Would someone with a Mac take a look at AltairZ80/mmd.c?

This is how it shows up in `vi`:

```
/***  mmd.c: Morrow Micro-Decision^M
 
    Created by Patrick Linstruth (patrick@deltecent.com)^M
 
    Permission is hereby granted, free of charge, to any person obtaining a^M
    copy of this software and associated documentation files (the "Software"),^M
    to deal in the Software without restriction, including without limitation^M
    the rights to use, copy, modify, merge, publish, distribute, sublicense,^M
    and/or sell copies of the Software, and to permit persons to whom the^M
    Software is furnished to do so, subject to the following conditions:^M
^M
    The above copyright notice and this permission notice shall be included in^M
    all copies or substantial portions of the Software.^M
^M
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR^M
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,^M
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL^M
    PETER SCHORN BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER^M
    IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN^M
    CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.^M
^M
    Except as contained in this notice, the name of Patrick Linstruth shall not^M
    be used in advertising or otherwise to promote the sale, use or other dealings^M
    in this Software without prior written authorization from Patrick Linstruth.^M
^M
    These functions support the Morrow Micro-Decision Models 2 and 3.^M
^M
    There are two devices defined, MMD and MMDM. The MMD device supports 4^M
    floppy drives and the console serial port.^M
^M
    The Micro-Decision's second serial (modem) port uses I/O ports 0xfe and 0xff.^M
    Z80 or 8080 programs can also communicate with the SIMH pseudo device via^M
    port 0xfe. Due to this conflict, the MMDM device is disabled by default. In^M
    order to use the modem port, execute "SET MMDM ENABLE". Note that when the^M
    MMDM device is enabled it will not be possible to use the SIMH pseudo device^M
    and CP/M utilities such as R.COM and W.COM.^M
^M
    Units:^M
^M
```

If i run `dos2unix` and `unix2dos` on it, `git diff` thinks a lot of lines have changed. It is this that I was trying to avoid doing again.

**Comment by markpizz** [comment]
This file has ssome very strange line endings.  Sort of a mixture of CRLF and LF.

It should be fixed with:
```
$ dos2unix mmd.c
$ dos2unix mmd.c
$ unix2dos mmd.c
```
And the results updated in a PR.

Running dos2unix many times on the same file, in general, has no effect if there are no mixed line endings.
The the unix2dos changes the LF line endings to CRLF.

vi (actually vim) on macOS will then display the files without any visible ^M, even though the line endings are actually there.

**Comment by deltecent** [comment]
Thanks. I wanted to verify that you were seeing the same thing. I will fix the line endings and submit a PR.

**Comment by markpizz** [comment]
This issue is fixed long ago.
