### ISSUE TITLE
CI: error MSB8020: The build tools for v141_xp (Platform Toolset = 'v141_xp') cannot be found

### ISSUE THREAD

**Issue by XVilka** [open-simh/simh#246]
I suppose GitHub Actions Windows image has changed recently?
```
** C:\Program Files\CMake\bin\cmake.exe -G "Visual Studio 17 2022" -A Win32 -T v141_xp -Wno-dev --no-warn-unused-cli -DSIMH_PACKAGE_SUFFIX:Bool=win32-xp -S D:\a\simh\simh -B D:\a\simh\simh\cmake\build-vs2022-xp
Not searching for unused variables given on the command line.
-- CMAKE_MODULE_PATH: D:/a/simh/simh/cmake;D:/a/simh/simh/cmake/installer-customizations
CMake Error at CMakeLists.txt:82 (project):
  Failed to run MSBuild command:

    C:/Program Files/Microsoft Visual Studio/2022/Enterprise/MSBuild/Current/Bin/amd64/MSBuild.exe
-- Configuring incomplete, errors occurred!

  to get the value of VCTargetsPath:

    MSBuild version 17.6.3+07e294721 for .NET Framework
    Build started 6/7/20[23](https://github.com/open-simh/simh/actions/runs/5205648567/jobs/9391334981?pr=239#step:4:24) 11:17:01 PM.
    
    Project "D:\a\simh\simh\cmake\build-vs2022-xp\CMakeFiles\3.[26](https://github.com/open-simh/simh/actions/runs/5205648567/jobs/9391334981?pr=239#step:4:27).3\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for v141_xp (Platform Toolset = 'v141_xp') cannot be found. To build using the v141_xp build tools, please install v141_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\a\simh\simh\cmake\build-vs2022-xp\CMakeFiles\3.26.3\VCTargetsPath.vcxproj]
    Done Building Project "D:\a\simh\simh\cmake\build-vs2022-xp\CMakeFiles\3.26.3\VCTargetsPath.vcxproj" (default targets) -- FAILED.
    
    Build FAILED.
    
    "D:\a\simh\simh\cmake\build-vs2022-xp\CMakeFiles\3.26.3\VCTargetsPath.vcxproj" (default target) (1) ->
    (PrepareForBuild target) -> 
      C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for v141_xp (Platform Toolset = 'v141_xp') cannot be found. To build using the v141_xp build tools, please install v141_xp build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\a\simh\simh\cmake\build-vs2022-xp\CMakeFiles\3.26.3\VCTargetsPath.vcxproj]
    
        0 Warning(s)
        1 Error(s)
    
    Time Elapsed 00:00:11.07
    

  Exit code: 1



Error running 'C:\Program Files\CMake\bin\cmake.exe -G "Visual Studio 17 2022" -A Win[32](https://github.com/open-simh/simh/actions/runs/5205648567/jobs/9391334981?pr=239#step:4:33) -T v1[41](https://github.com/open-simh/simh/actions/runs/5205648567/jobs/9391334981?pr=239#step:4:42)_xp -Wno-dev --no-warn-unused-cli -DSIMH_PACKAGE_SUFFIX:Bool=win32-xp -S D:\a\simh\simh -B D:\a\simh\simh\cmake\build-vs2022-xp' command: Generate phase exited with non-zero status: 1
```
cc @bscottm

**Comment by bscottm** [comment]
Encountered the same off my `cmake-sanitize` branch. Looks like either MS finally deprecated XP support in VS 2022, the Chocolatey installer changed, or the Window image. Investigating.

**Comment by markpizz** [comment]
Like all other PRs, you should base the required change on what is at the HEAD of the github.com/open-simh/simh master branch.

This specifically avoids sneaking in unrelated personal changes you may have in your personal master branch.

**Comment by bscottm** [comment]
@sethm, @pkoning2:  Fix is in PR #249 (merged fixes from my `cmake-santizer` branch back into my fork's `master` to minimize disruptions.) Respectfully request expedited review.

**Comment by pkoning2** [comment]
> @sethm, @pkoning2: Fix is in PR #249 (merged fixes from my `cmake-santizer` branch back into my fork's `master` to minimize disruptions.) Respectfully request expedited review.

Thanks.  I hope Seth or someone else can review this; I know nothing about that machinery.

**Comment by pkoning2** [comment]
Scott, anyone is allowed to comment.  But I don't see why Mark made that comment; the PR appears to be against the HEAD of the master branch, as is indeed the normal procedure.

**Comment by sethm** [comment]
> Thanks. I hope Seth or someone else can review this; I know nothing about that machinery.

My GitHub Actions knowledge is not thorough, but I'll take a look

**Comment by markpizz** [comment]
I made the comment as a reminder since the original cmake PR got merged with several unrelated and irrelevant to the point of the PR changes included.

**Comment by bscottm** [comment]
> Scott, anyone is allowed to comment. But I don't see why Mark made that comment; the PR appears to be against the HEAD of the master branch, as is indeed the normal procedure.

Paul: I solicited Seth and you for feedback because this presented an opportunity to add the sanitizer work, if desired. However, since the Windows XP build is a blocker for other PRs, I took the initiative to pull it over to my fork's master branch.

Anyone can comment. And anyone can respond to those comments,
