### ISSUE TITLE
PDP11: RC: disk "footer" is still added with noautosize

### ISSUE THREAD

**Issue by al20878** [open-simh/simh#252]
- #### Context
I used "set noautosize" yet a newly created disk image still shows the last sector appendage...  How to disable this with commands?
I know I can use "zap", but I just don't want to have it there from the get-go.

```
$ pdp11
PDP-11 simulator Open SIMH V4.1-0 Current        git commit id: ad529d86
sim> set cpu 11/20 56k
sim> set noautosize
sim> set noautosize
%SIM-ERROR: Autosizing is already disabled!
sim> set rc ena
sim> show rc
RC      address=17777440-17777457, vector=210, BR5
        64KW, not attached, 1P
        autosize
sim> att rc rc.dsk
%SIM-INFO: RC: Creating new file: rc.dsk
%SIM-INFO: RC: buffering file in memory
sim> det rc.rc.dsk
sim> ! ls -l rc.dsk
-rw-rw-r--+ 1 User None 131584 Jun  9 13:35 rc.dsk
```
`rc.dsk` is expected to have the size of 131072, and inspection of the file shows the "footer" appended.
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

Expected with noautosize is not to get anything extra in the disk images, no?
I have my own tweaked version of the simulator code that disables it for good, but this one was built from out of github code, and I recalled seeing a "recipe" to disable the footer with the noautosize command.  Obviously, it did not work...
Even if I use `set rc noautosize`, it still gets the "footer appended":
```
sim> set rc 4p
sim> set rc noauto
sim> show rc
RC      address=17777440-17777457, vector=210, BR5
        256KW, not attached, 4P
        noautosize
sim> att rc rc.dsk
%SIM-INFO: RC: Creating new file: rc.dsk
%SIM-INFO: RC: buffering file in memory
sim> det rc
sim> ! ls -l rc.dsk
-rw-rw-r--+ 1 User None 524800 Jun  9 13:45 rc.dsk
```
The expected file size has to be 524288 (the actual again is 1 sector more, and that is exactly the "footer").
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Your original "problem" with autosizing containers was that "your" data was modified.  Actually none of your data was modified, but the file was extended to include the footer.  NOAUTOSIZE avoids changing any of your existing disk containers when you want to use the data in some context outside of simh.  A newly created container has none of your data and thus its full relevant attributes are stored in the "footer".  As you've already stated, you can then zap that container to remove the footer if you decide you want to use the file externally or just don't want the footer.

FYI, "inspection" of the container file can be done with "DISKINFO containerfile" which will illuminate the details in any disk footer, or and report the container file size.

The github.com/simh/simh repo has numerous bug fixes and enriched capabilities in the disk domain.  One feature that would potentially be relevant to what you've state here is a feature called AUTOZAP.  As the name implies, disk oriented units with with AUTOZAP enabled will automatically be zapped on detach (or simulator exit).   SET AUTOZAP is a global command affecting all disk devices, while each unit can optionally enable or disable AUTOZAP.  Autosizing and Autozap can be enabled together to gain the benefits of autosizing while also assuring that containers don't end up with unwanted meta data.

**Comment by al20878** [comment]
Well, RC as well as RF are those disks than you can "extend" by adding platters...  When you do that, the footer comes in the way as "data".  Good advertising, but I'm not going to use simh/simh.  (Funny that yourself is acknowledging that the footer is an extremely annoying and redundant/useless feature if there's "autozap" now.  LOL)  TY, though.

So it's yet another feature...

**Comment by markpizz** [comment]
> Well, RC as well as RF are those disks than you can "extend" by adding platters... 

Please elaborate on how this would work with real hardware.  How are additional platters connected to the original disk drive (screws?, rubberbands?, glue?)?  I imagine that this would be done with the OS running and the existing platters spinning, right?

Apart from the mechanics, what about the data (file systems) on the original platters?  How does the OS leverage the space beyond the original platters after additional platters were added?

> Funny that yourself is acknowledging that the footer is an extremely annoying and redundant/useless feature if there's "autozap" now. LOL) TY, though.

I would never use AUTOZAP.  AUTOZAP was added for folks like you.

**Comment by pkoning2** [comment]
RC11 controllers support 1-4 RS64 drives; RF11 controllers support 1-8 drives.  Adding one is a matter of plugging one in.  I don't remember how electrically that works, but conceptually it's no different from adding another RP04 to an RH11.

As for the FS, it might care, or not.  RT11 wouldn't have much trouble, nor would RSTS.  That assumes you have an FS in the first place.  RSTS doesn't put file systems on the RC11, it uses them simply as swap space.  RT11 does (if you want to).

**Comment by al20878** [comment]
Snarky, aren't you?

FYI, the additional "platters" are actually the units daisy-chained to the controller.  Software talks to single controller, but I/O "spills over" from one unit to the other, so they behave as a single drive.

**Comment by al20878** [comment]
bq.  I would never use AUTOZAP. AUTOZAP was added for folks like you.

Not to worry about me, I'm not going to ever use it, either: the whole simh/simh thing.

**Comment by markpizz** [comment]
@pkoning2 said:
> RC11 controllers support 1-4 RS64 drives; RF11 controllers support 1-8 drives. 

I was completely unaware of this monkey business for these drive types.  Let me ponder this for a while.

**Comment by pkoning2** [comment]
It's well documented in the hardware docs, including the Peripherals handbook.  Admittedly I have only seen 1-platter RC and RF setups in the wild, but it's clear the other cases are supported.  For example, the RSTS docs clearly say that 1-8 RF platters work.  (Don't remember RC; those were only supported in V4 and the last I used that was 1974.)  And even the last RSTS (V10.1) includes the code to autosize RF11 configs to determine the platter count.

**Comment by ethandicks** [comment]
On Fri, Jun 9, 2023 at 5:29 PM Mark Pizzolato ***@***.***> wrote:
> @pkoning2 said:
> RC11 controllers support 1-4 RS64 drives; RF11 controllers support 1-8 drives.
>
> I was completely unaware of this monkey business for these drive types. Let me ponder this for a while.

The same thing is true for DF32/DS32 and RF08/RS08 on PDP-8s.  You
just plug in drive units that don't have the controller backplane
populated and it extends the storage (i.e., one DF32 and 0 to 3 DS32
for 32Kwords up to 128Kwords).  No changes to the controller.

-ethan

**Comment by markpizz** [comment]
> It's well documented in the hardware docs, including the Peripherals handbook. Admittedly I have only seen 1-platter RC and RF setups in the wild, but it's clear the other cases are supported. For example, the RSTS docs clearly say that 1-8 RF platters work. (Don't remember RC; those were only supported in V4 and the last I used that was 1974.) And even the last RSTS (V10.1) includes the code to autosize RF11 configs to determine the platter count.

OK, so conceptually, what does the storage look like when additional platters are added to the RC11 or RF11?  Specifically is the new platter logically space beyond the prior platter(s).  I'm asking to clarify my understanding of how this multi-platter arrangement relates to other disk types that begin and end their life with a fixed number of platters.  In these other cases, the logically addressable space on the disk starts at sector 0 of track 0 of platter 0.  After addressing n sectors (where n is the number of sectors per track), the next sector's address is sector 0 of track 0 of platter 1, and this follows until all platters have been referenced and then things move to sector 0 of track 1, of platter 0....  Does this reference model apply to the RC disks?  If so, the original data would be interleaved with the prior data when an additional platter were added.  This would seem to make the original data sort of lost.  Alternatively, if the newly added platter(s) were to be logically appended to the original platter(s), then data on the new platters would be additional tracks on the RC controller and the physical platter number would be derived from the track number... and thus there would be more 1 platter cylinders.  How does this work?

**Comment by al20878** [comment]
They are called platters because the (additional) units have only one recording surface inside (the top of the physical disk).  So when you added a platter, it would not go "on top" of the other platters, logically, as it to form a "higher" cylinder (that would have added heads, if it did).  Instead, the unit ID serves as the address extension.  The entire Disk Address (DA) is formed by three parts, from high order to the low order: drive number bits, track number bits, and sector number (RC) or word number (RF -- it's a word-addressable disk).  So when you start IO, it operates the DA as a single entity, so it'd count sectors(words), overflowing into tracks, and then overflowing into the drive ID.  So even though IO crosses the track boundaries, as usual in most drives, it also crosses the unit boundaries, continuing with the next platter (at track 0, sector / word 0).
