### ISSUE TITLE
windows-build\lib\Release\\libpng16.lib' was created by a different version of the compiler than other objects like '..\BIN\NT\Project\simh\SEL32\Win32-Release\scp.obj'

### ISSUE THREAD

**Issue by XVilka** [open-simh/simh#255]
```
LINK : fatal error C1047: The object or library file '..\..\windows-build\lib\Release\\libpng16.lib' was created by a different version of the compiler than other objects like '..\BIN\NT\Project\simh\SEL32\Win32-Release\scp.obj'; rebuild all objects and libraries with the same compiler [D:\a\simh\simh\Visual Studio Projects\SEL32.vcxproj]
LINK : fatal error LNK1257: code generation failed [D:\a\simh\simh\Visual Studio Projects\SEL32.vcxproj]
Done Building Project "D:\a\simh\simh\Visual Studio Projects\SEL32.vcxproj" (default targets) -- FAILED.
Done Building Project "D:\a\simh\simh\Visual Studio Projects\Simh.ci.sln" (default targets) -- FAILED.

Build FAILED.
```
https://github.com/open-simh/simh/actions/runs/5322905030/jobs/9639976170#step:9:8992

**Comment by markpizz** [comment]
I'll be fixing the cause of this later today, without regard to the insane design.

**Comment by pkoning2** [comment]
Thanks, much appreciated.  I sure wish MS had competent engineers.

**Comment by markpizz** [comment]
@XVilka, did you notice this on a local in your system or dig it out of a CI log?

**Comment by XVilka** [comment]
@markpizz CI. Noticed while checking the repo

**Comment by markpizz** [comment]
@XVilka , Since you've been digging through the repo CI logs already, can you see if the current build produce some lines like this:
```
1>_MSVC_VER=19.34.31933
1>_MSVC_TOOLSET_VER=v143
1>_MSVC_TOOLSET_DIR=14.34.31933
```
If find them, will you please copy them here.

Thanks.

**Comment by XVilka** [comment]
> @XVilka , Since you've been digging through the repo CI logs already, can you see if the current build produce some lines like this:
> 
> ```
> 1>_MSVC_VER=19.34.31933
> 1>_MSVC_TOOLSET_VER=v143
> 1>_MSVC_TOOLSET_DIR=14.34.31933
> ```
> 
> If find them, will you please copy them here.
> 
> Thanks.

No exactly these lines, but:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.36.32532\bin\HostX86\x86\CL.exe
MSBuild version 17.6.3+07e294721 for .NET Framework
```
Looks like some recent MSVC update broke something.

**Comment by markpizz** [comment]
I know nothing about the failure of the cmake based build process.  However, the legacy windows build VS2022 build that failed (which I think was the motive for this issue report) now builds successfully:

https://github.com/open-simh/simh/actions/workflows/windows_build.yml
