### ISSUE TITLE
Appveyor updates

### ISSUE THREAD

**Issue by bscottm** [open-simh/simh#268]
PR #267 has updates to appveyor.yml that fixes a premature build termination when `cmake` warns the user about outdated `cpack` (the packager). Apparently, writing to the MS `Warning` stream will cause Appveyor to terminate the build if invoked by PowerShell. (Note: The MS C runtime has more than `stdin`, `stdout` and `stderr`. There's also `stdwarn` -- that's the offending critter.)

Appveyor's technical support said to rewrite the build stanzas with `cmd` -- DOS will just not die! [The complete build](https://ci.appveyor.com/project/bscottm/open-simh) completes successfully, CMake warnings and all.

Cut down the number of builds actually done to VS 2022, 2019, 2017, XP variants and Ubuntu 22 and 20. The older builds are still in the matrix, just commented out.

Also bumped library version numbers for libpng16, SDL and SDL_ttf to reflect newer releases.

**Comment by pkoning2** [comment]
This has been merged.
