### ISSUE TITLE
Tags for releases in branch Supnik-Current

### ISSUE THREAD

**Issue by wfjm** [open-simh/simh#28]
The branch `Supnik-Current` used to track Bob's releases of SimH-Classic.  
And up to 2020 Bob's releases were properly tagged, last tag is [v3.11-1](https://github.com/open-simh/simh/releases/tag/v3.11-1).  

With pull requests [14](https://github.com/open-simh/simh/pull/14) and [23](https://github.com/open-simh/simh/pull/23) the releases `v3.12` and `v3.12-2` were somehow added to branch `Supnik-Current`.  
The pull 14 is labeled _These commits are part Bob's of simh v3.12_.
The pull 23 in fact has two commits, the first apparently reflects `v3.12-2`, the second an additional change.

What is the purpose of the `Supnik-Current` branch in `open-simh` ?  
Pull's are including _are part Bob's ..._, or mix Bob's releases with other changes.
There are no tags for v3.12 and v3.12-2.  
And maybe that's not even possible now.

I'd highly appreciate if Bob's releases are properly reflected in the `Supnik-Current` branch.  
As it used to be in `simh/simh`, where all Simh_Classic releases from `v2.3a` to `v3.11-1` are easily accessible.

In case of SimH-Classic we have proper releases, and that should be imho visible as tags in open-simh.

**Comment by pkoning2** [comment]
As far as I know that branch is supposed to track Bob's work.  If it doesn't that should be fixed.  Mark Pizzolato has contributed the commits for this; I don't know the details (other than that things seem to build and run).

**Comment by wfjm** [comment]
@pkoning2 : I checked the `Supnik-Current` branch. 
I checked out commit 14dccaa which is labeled `simh v3.12-2`.
And downloaded `simhv312-2.zip` from http://simh.trailing-edge.com.  
And diff'ed the two source trees and got
```
  Only in os-simh/simh: .git
  Only in os-simh/simh: .gitattributes
  Only in os-simh/simh: .gitignore
  Only in os-simh/simh: 0readme_311.txt
  Only in te-simh/sim/VAX: vmb.exe
  Only in os-simh/simh: Visual Studio Projects
```
Both file trees are identical at the source files level.
A bit astonishing is that `vmb.exe` is in Bob's zip fille, but but in the open-simh branch.  
The open-simh branch contains `Visual Studio Projects` which is not in Bob's zip file.

So the `Supnik-Current` branch somehow tracks Bob's work.

What is missing are proper tags, as we had them before.  
Why is there no `v3.12-2`, like we had https://github.com/open-simh/simh/releases/tag/v3.11-1 ?  
This tag should refer to 14dccaa .  
Tags can't be set as part of a merge request (as far as I know).  
So this must be done by a member of the [steering group](https://github.com/open-simh/simh/blob/master/SIMH-SG.md).

**Comment by wfjm** [comment]
@markpizz might comment on why `vmb.exe` is missing in `Supnik-Current`.  
@pkoning2 : only a tag should be set, without defining a release. I think, git releases should be reserved to V4 releases, if there ever will be some. Is there any reason for _not_ defining a tag for Bob's V3 releases ?

**Comment by pkoning2** [comment]
I don't know much about Git tags.  It seems easy enough to set a tag on a given commit.  If it isn't part of merge requests, then it would help for people who know about tags to point out the need for one to be created.
I'll take care of the 3.12-2 tag.

**Comment by pkoning2** [comment]
The missing bit of knowledge is that after I make the tag in my workspace I have to use --tags on the push to get it across.  Done.

**Comment by markpizz** [comment]
The absolute and formal place where simh v3 and its releases are managed is https://simh.trailing-edge.dom.

The Supnik-Current branch contains what Bob Supnik has provided to me directly (or left on the above mentioned site) which served as the visible evolution of the v3 code branch.  However, its primary purpose has (and still is) a reference point that simplifies my visibility of the changes to the v3 source code so that it can be merged into the v4 code base.  The v4 codebase is a proper superset of the v3 code.

**Comment by pkoning2** [comment]
That's what I thought.  
So it does mean that we should try to have the branch reflect what's in the official release; presumably mismatches are not intended and should be corrected.   The missing tag I just added is an example.
Which makes me wonder: why would vmb.exe not appear in the branch?

**Comment by wfjm** [comment]
@markpizz wrote:
> The absolute and formal place where simh v3 and its releases are managed is https://simh.trailing-edge.com/.

That I perfectly know. And that the `Supnik-Current` branch is primarily a staging area allowing  easy inclusion of V3 developments into V4.

Nevertheless, having tags of Bob's releases is highly convenient.  
It allows to inspect the V3 code base, and use `git diff` to see the changes between Bob's releases.  
Without tags one needs a separately maintained mapping of commits to Bob's releases, and that would be silly.

So all I was asking for is to continue with tagging Bob's releases in `open-simh/simh` as it was done all the time in `simh/simh`.

**Comment by wfjm** [comment]
@pkoning2 : thanks for adding the tag ! You wrote

>  Which makes me wonder: why would vmb.exe not appear in the branch?

Only @markpizz can answer that.  
Beyond that the issues seems 'done', feel free to close it when @markpizz has answered on `vmb.exe`.

**Comment by markpizz** [comment]
Like I said, Bob sends me zip or .7z files of things in his working directory from time to time.  Maybe most of the directory or maybe just a few files.

When I dropped what he sent me into a working directory those contents may or may not have had a vmb.exe file.  However, although vmb.exe has changed significantly in the v4 branch, what Bob packages today exists from way back when the vax780 was first included in v3, so given the sole purpose of Supnik-Current of merging v3 code changes into the v4, absolutely no need to worry about vmb.exe.  

Apart from the basic merging of code changes, the repo has always had a .gitignore file which explicitly ignores various file types which might randomly end up in working directories and, in general, should never be added to the repo.  This .gitignore list includes .exe, .bin .obj, .o and many other file types.  The small handful of binary "Blob" files that actually are usefully a part of the simh v4 project codebase must be explicitly "git add -f" to step aside from the .gitignore default behavior.

Your desire to change the purpose/role of the Supnik-Current branch to be something other than it has been is out of scope for the v4 based open-simh project.
