### ISSUE TITLE
Itanium

### ISSUE THREAD

**Issue by Torinde** [open-simh/simh#288]
There is IA-64 instruction set simulator [[1]](http://ski.sourceforge.net/), currently being maintained at github [[2]](https://github.com/trofi/ski) and there is an executable toolkit [[3]](http://www.irisa.fr/caps/projects/ArchiCompil/iato/)

Collaborating with @trofi may be relevant for your project.

Also, since you have already HP 3000/PA-RISC, adding HP 9000 will complete the series.

**Comment by pkoning2** [comment]
Unfortunately that simulator is GPL, which is incompatible with the SIMH license.  And since it's mostly code produced by a large company, it's not likely it would be feasible to get the license changed to be compatible.
