### ISSUE TITLE
Duplicate register names in pdp6_dtc.c

### ISSUE THREAD

**Issue by markpizz** [open-simh/simh#31]
Lines 73 to 77 of pdp6_dtc.c contain:
```
REG                 dct_reg[] = {
    {BRDATA(BUFF, dct_buf, 16, 36, NUM_DEVS_DCT), REG_HRO},
    {BRDATA(BUFF, dct_acc, 16, 36, NUM_DEVS_DCT), REG_HRO},
    {0}
};
```
Both of these REGister entries have the same name, but refer to different data.  The names should be different.

**Comment by rcornwell** [comment]
Changed second entry to ACC.
