### ISSUE TITLE
ibmpc.c calls reg_dev function with too few arguments

### ISSUE THREAD

**Issue by LegalizeAdulthood** [open-simh/simh#35]
https://github.com/open-simh/simh/blob/adfcff49b7b75c2d32a78daf38408cc6206c830e/Intel-Systems/ibmpc/ibmpc.c#L88-L91

The function `reg_dev` takes three arguments but these calls only supply 2 arguments.

**Comment by LegalizeAdulthood** [comment]
The argument is unused by the function, so I'm going to issue a pull request that simply drops the argument from the declaration/definition.

**Comment by markpizz** [comment]
You should actually ONLY build targets that the makefile builds with "make all" in the current code base.

**Comment by LegalizeAdulthood** [comment]
Eh... this code is seriously busted:
- Instead of declaring functions in headers, they are declared in every source file that uses the functions and the declarations at point-of-use don't match the declarations at point-of-definition
- Integers are supplied as arguments that are expected to be pointers (e.g. `DEVICE *`)

I'm unsure of the intention of the original author of the code.  So instead of attempting to fix the build errors myself, I'm going to leave this issue open for someone else to address.

**Comment by markpizz** [comment]
The author (@nj7p ) has had this simulator on hold for several years while focusing on enhancing and simplifying other simulators.  He plans to eventually get back to it.  For now it should just be left alone.

**Comment by pkoning2** [comment]
Closing for now.
If and when this simulator is revived the issue can be reopened (or, likely, will have been resolved by then).
