### ISSUE TITLE
command completion not work...???

### ISSUE THREAD

**Issue by drforbin** [open-simh/simh#399]
Running 4.1 current.
I compiled this on raspberrypi 1
The issue is I don't seem to have command completion <TAB> like in bash.
This works when compiled on desktop gentoo.

Any ideas?

**Comment by pkoning2** [comment]
Make sure "editline" (and "editline-dev" or some similar package name) is installed

**Comment by drforbin** [comment]
libedit?

**Comment by pkoning2** [comment]
> libedit?

Yes, I guess that's what it is called.  The line editing package, non-GPL flavor of "readline".

**Comment by drforbin** [comment]
Thank you so much that worked.

**Comment by pkoning2** [comment]
Thanks for the confirmation.
