### ISSUE TITLE
CH11 may be on BR5, not BR6 - Requires independent confirmation with real hardware

### ISSUE THREAD

**Issue by dseagrav** [open-simh/simh#43]
When implementing a CH11 workalike on a physical KS10, I observed that ITS would crash if there was a nontrivial amount of DZ11 traffic occurring simultaneously with network activity. This was traced to remote terminal connections at BR6 pre-empting the DZ11 interrupt handler at BR5, corrupting the state of the terminal IO handler. Crashes were usually in the vicinity of TYP1B.

This would indicate that the CH11 is supposed to be at BR5, as described in AIM-628, instead of BR6. Moving my CH11 workalike to BR5 resolved the crashes.

I do not have a MIT-made CH11 to confirm this with. I do not know if simh exhibits this behavior. I do believe that simh, similar to klh10, places the CH11 at BR6 by default.

Please take this issue under advisement until someone with better information is able to confirm or disprove my interpretation of events.

**Comment by dseagrav** [comment]
I apologize unreservedly for wasting everyone's time and energy. simh places the CH11 at BR5, not BR6.

Issue closed, and again I apologize on all possible bases.

**Comment by dseagrav** [comment]
I apologize unreservedly for wasting everyone's time and energy. simh places the CH11 at BR5, not BR6.

Issue closed, and again I apologize on all possible bases.

**Comment by larsbrinkhoff** [comment]
Let's CC @rcornwell.  Do you have your KS10 CH11 set to BR5?

**Comment by larsbrinkhoff** [comment]
I think @rcornwell fixed this in his "sims" repository.

**Comment by pkoning2** [comment]
I just confirmed that both pdp11 and pdp10-ks default CH to BR5.
