### ISSUE TITLE
3b2 - build errors/warnings 

### ISSUE THREAD

**Issue by markpizz** [open-simh/simh#76]
```
1>3b2_stddev.c
1>..\3B2\3b2_stddev.c(297) : error C2065: 'uint32_t' : undeclared identifier
1>..\3B2\3b2_stddev.c(297) : error C2146: syntax error : missing ';' before identifier 'catchup_ticks'
1>..\3B2\3b2_stddev.c(297) : error C2065: 'catchup_ticks' : undeclared identifier
1>..\3B2\3b2_stddev.c(308) : error C2065: 'catchup_ticks' : undeclared identifier
1>..\3B2\3b2_stddev.c(308) : error C2065: 'uint32_t' : undeclared identifier
1>..\3B2\3b2_stddev.c(308) : error C2146: syntax error : missing ';' before identifier 'delta'
1>..\3B2\3b2_stddev.c(308) : warning C4552: '*' : operator has no effect; expected operator with side-effect
1>..\3B2\3b2_stddev.c(311) : error C2065: 'catchup_ticks' : undeclared identifier
1>..\3B2\3b2_stddev.c(312) : error C2065: 'catchup_ticks' : undeclared identifier
```
```
1>3b2_cpu.c
1>..\3B2\3b2_cpu.c(879) : warning C4101: 'r' : unreferenced local variable
1>..\3B2\3b2_cpu.c(1035) : warning C4101: 'r' : unreferenced local variable
1>
```

**Comment by Rhialto** [comment]
Essentially the same thing as #74. Pretty much all compiters include `<stdint.h>` from `<sim_defs.h>` except MSVC: `#elif defined(_MSC_VER) && (_MSC_VER < 1600)`. Maybe these are the versions that are not really C compilers because they do not implement even C99 features?

**Comment by Rhialto** [comment]
I'll bite. #78 should fix it.

**Comment by tlhackque** [comment]
An alternative to consider would be to typedef the missing types for MSVC in sim_defs.h, 

e.g. `typedef uint32 uint32_t;` (and any others from stdint: that are missing)

This has the advantage that the standard typedefs would be available for any libraries or other code that's used, now or in the future.  It also fixes all current and future references to stdint-style declarations in project code.

OTOH, uniformity has its advantages, and we use the local types almost everywhere.

I could go either way, but the alternative seems worth considering.

**Comment by Rhialto** [comment]
On Sun 23 Oct 2022 at 09:00:46 -0700, Timothe Litt wrote:
> An alternative to consider would be to typedef the missing types for
> MSVC in sim_defs.h, 

That is usually my approach when trying to be compatible with old stuff.
You can then write your own code in the modern way (whatever that is)
without worries, and only for the old compiler/operating system/whatever
you need to do potentially weird or ugly stuff.

> e.g. `typedef uint32 uint32_t;` (and any others from stdint: that are
> missing)

Changing the types in open-simh would be an easy mechanical task but it
would mean a lot of churn; sometimes that's a reason not to do it.

But given how automatically I used a modern type when I needed to add a
declaration, I'm guessing that other people might have the same
automatism.

**Comment by tlhackque** [comment]
I'm **not** suggesting a mass edit, at least not for now.

Simply change `sim_defs.h` for the deficient compilers so we define the _**_t**_ types.

No need to change existing code, no churn.

There would be a mix, but it would be harmless.

A decision to change everything over to the **__t_** types is a bigger one.  I'm not
sure that's a good idea, since there are simulators not in the repo, notably the
3.9 branch.  Making those merges harder would not be a good thing.

**_Maybe_** when the branches coalesce to V5.

In the meantime, both types would be available everywhere, which I think simplifies life for everyone.

That may also be the right long-term solution.

**Comment by markpizz** [comment]
> I'm not suggesting a mass edit, at least not for now.
>
> Simply change sim_defs.h for the deficient compilers so we define the _t types.

The only problem is at some point,  the Microsoft compilers/includes provide the standard typedefs, and thus redefining them slightly differently might lead to errors.

> No need to change existing code, no churn.

Absolutely should avoid the churn.

> There would be a mix, but it would be harmless.

Except for the case I mentioned above...

> A decision to change everything over to the _t types is a bigger one. I'm not sure that's a good idea, since there are simulators not in the repo, notably the 3.9 branch. Making those merges harder would not be a good thing.

Agreed again.

using the existing simh types is simplest and safest.

**Comment by markpizz** [comment]
This would have been visible very early, before the 3b2 changes were merged if the CI build that historically ran on Windows using this compiler was running now on the open-simh/simh repo.  @larsbrinkhoff originally set that up.  It appears that these builds are working on his open-simh fork, but not on the main repo.

**Comment by tlhackque** [comment]
`sim_defs.h` is already conditional on _MSC_VER, and includes `stdint.h` for recent versions.

The only change is defining the standard types for the older versions.  Typdefing them to the simh types is harmless, 

If some other code defines the standard types other than in terms of the simh types, it would be broken with any current compiler, including M$. And keeping all such work-arounds in one place is more maintainable.

I don't see the risk of making life simpler.

**Comment by markpizz** [comment]
> sim_defs.h is already conditional on _MSC_VER, and includes stdint.h for recent versions.
>
> The only change is defining the standard types for the older versions. Typdefing them to the simh types is harmless,

Agreed, but you've got to precisely identify which MSC_VER has the standard types silently defined.to avoid potential conflicting redefinitions.

Additionally, the current code builds on Itanium and Alpha VMS environments using DEC C.  If you start using standard types then they also need to be addressed for this environment.
