### ISSUE TITLE
3b2 does not make

### ISSUE THREAD

**Issue by ram064** [open-simh/simh#79]
On Liinux, 'make 3b2-400' fails because it claims that there is no rule for 3b2_cpu.c, as:
*** 3b2-400 Simulator being built with:
*** - compiler optimizations and no debugging support. GCC Version: 11.2.0.
*** - dynamic networking support using Linux provided libpcap components.
*** - Local LAN packet transports: PCAP VDE TAP
*** - Per simulator tests will be run.
***
make: *** No rule to make target '3B2/3b2_cpu.c', needed by 'BIN/3b2'.  Stop.

**Comment by markpizz** [comment]
Please provide MORE of the details asked for when you created this issue.

Specifically:
1- ALL of the output produced by the make that failed.
2- WHAT git commit were you compiling?

**Comment by pkoning2** [comment]
Works fine in the current version.
